# Generated by Django 2.2.6 on 2019-11-04 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModelMachine',
        ),
        migrations.RemoveField(
            model_name='mlmodel',
            name='process',
        ),
        migrations.AddField(
            model_name='awsinstance',
            name='ml_models',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_by', to='ml_core.MLModel'),
        ),
        migrations.AddField(
            model_name='process',
            name='ml_models',
            field=models.ManyToManyField(to='ml_core.MLModel'),
        ),
    ]
