# Generated by Django 2.2.6 on 2019-11-04 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_core', '0003_auto_20191104_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_by', to='ml_core.AwsInstance')),
            ],
        ),
        migrations.RemoveField(
            model_name='mlmodel',
            name='ml_models',
        ),
        migrations.AlterField(
            model_name='process',
            name='ml_models',
            field=models.ManyToManyField(to='ml_core.ModelMachine'),
        ),
        migrations.AddField(
            model_name='modelmachine',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_by', to='ml_core.MLModel'),
        ),
    ]
