# Generated by Django 2.2.6 on 2019-11-04 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_core', '0004_auto_20191104_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmachine',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_by', to='ml_core.Process'),
        ),
    ]
