# Generated by Django 2.2.6 on 2019-11-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_core', '0006_auto_20191104_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='slug',
        ),
    ]
