# Generated by Django 2.2.6 on 2019-11-10 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_core', '0008_auto_20191110_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='ml_models',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_by', to='ml_core.AwsInstance'),
        ),
    ]
