# Generated by Django 2.2.6 on 2019-11-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_core', '0009_mlmodel_ml_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='models',
            field=models.ManyToManyField(to='ml_core.MLModel'),
        ),
    ]
